# Generated by Django 3.2.1 on 2021-05-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='subkect',
            new_name='subject',
        ),
    ]
