# Generated by Django 3.2.1 on 2021-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='description',
        ),
        migrations.AddField(
            model_name='clients',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
