# Generated by Django 3.2.1 on 2021-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210513_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='client/')),
            ],
        ),
        migrations.DeleteModel(
            name='clients',
        ),
    ]
